export { default as HomePage } from "./home"
export { default as Enquire } from "./enquire"
export { default as Applications } from "./applications"
export { default as Login } from "./login"
export { default as Signup } from "./sign-up"